### PR TITLE
Change name

### PR DESCRIPTION
**Pull request by nhanamrafee**
I just changed my name.

### CODE REVIEW

**Comment by gparce1** [comment]
@nhanamrafee Just noticed that you're trying to merge your develop branch into my branch. You should be merging your **develop** branch into your own **master** branch, like this
image
 I'm going to close this PR, please create another one.

Gene

**Comment by nhanamrafee** [comment]
Oops! What is a PR?

Thanks,
Hana

**Comment by gparce1** [comment]
@nhanamrafee A pull request. If you go to your github, in the "compound interest calculator" repository, you'll see a "new pull request" button.

image

**Comment by nhanamrafee** [comment]
Hi Gene,

I got a new MacBook and Atom isn’t working on it (I can show you later in class), so I figured I would use Dreamweaver to do the coding for this first assignment. I just don’t know if I can connect it to Git Hub or how to upload the Git Hub file to Dreamweaver. Do you know what I can do?

Thanks so much!
Hana (DES 350)

**Comment by nhanamrafee** [comment]
Hi again,

I just figured out how to upload the files through the Git Hub folder on my computer. I just don’t know how to do the pull request after I’m done editing the file. 

Thanks again!
Hana

**Comment by nhanamrafee** [comment]
Hi Gene,

Another update:

I am trying to create a pull request, but it says that there’s nothing to compare between my original and my developed file. I might have accidentally updated the original with it. I did hit the “commit” button and you can see what changes I made in the history of the file. Let me know if there’s anything I should do with it.

Thanks,
Hana

**Pull request closed without merging**
